name: Android CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:

    runs-on: macos-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Navigation test
        uses: ReactiveCircus/android-emulator-runner@v2.6.2
        run: ./gradlew :navigation:connectedCheck --stacktrace
        with:
          api-level: 21
          profile: pixel